ARG HOST="my-own-database.com"
ARG USER="my-replication-user"
ARG DATABASE_NAME="postgres"
ARG PRE_FILE="pre.sql"
ARG POST_FILE="post.sql"
ARG LOCALE_LANG="en_DK"
ARG TZ="Europe/Copenhagen"

FROM ghcr.io/frederikhs/local-db-copy:latest
# runs onbuild instructions configured by build arguments
